name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/ellipse_181_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/group_24_x2.svg
  - assets/vectors/ellipse_16_x2.svg
  - assets/vectors/ellipse_192_x2.svg
  - assets/vectors/ellipse_172_x2.svg
  - assets/vectors/ellipse_19_x2.svg
  - assets/vectors/ellipse_162_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/ellipse_18_x2.svg
  - assets/vectors/group_241_x2.svg
  - assets/vectors/ellipse_17_x2.svg
  - assets/vectors/group_242_x2.svg
  - assets/vectors/ellipse_161_x2.svg
  - assets/vectors/ellipse_191_x2.svg
  - assets/vectors/ellipse_182_x2.svg
  - assets/vectors/ellipse_171_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/group_243_x2.svg

